version: "3.1"

services:
  catalog-mongo:
    build:
      context: ./mongodb
      dockerfile: ./Dockerfile
    container_name: catalog-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    logging:
      driver: none
    networks:
      - catalog
    ports:
      - 27017:27017

  catalog-backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - BACKEND_PORT=3355
      - DEBUG="catalog:*"
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=test
    ports:
      - "3355:3355"
    container_name: catalog-backend
    depends_on:
      - catalog-mongo
    networks:
      - catalog
    restart: unless-stopped

networks:
  catalog:
    driver: bridge

