export const FETCH_FILTERS = "CATALOG/FETCH_FILTERS";
export const UPDATE_FILTERS = "CATALOG/UPDATE_FILTERS";
export const APPLY_FILTERS = "CATALOG/APPLY_FILTERS";
export const RESET_FILTERS = "CATALOG/RESET_FILTERS";
export const FETCH_PRODUCTS = "CATALOG/FETCH_PRODUCTS";
export const UPDATE_PRODUCTS = "CATALOG/UPDATE_PRODUCTS";
export const ADD_PRODUCTS_PAGE = "CATALOG/ADD_PRODUCTS_PAGE";
export const SHOW_PRODUCTS_LOADER = "CATALOG/SHOW_PRODUCTS_LOADER";
export const HIDE_PRODUCTS_LOADER = "CATALOG/HIDE_PRODUCTS_LOADER";
export const SHOW_FILTERS_LOADER = "CATALOG/SHOW_FILTERS_LOADER";
export const HIDE_FILTERS_LOADER = "CATALOG/HIDE_FILTERS_LOADER";
export const UPDATE_CAN_LOAD_MORE_PRODUCTS =
  "CATALOG/UPDATE_CAN_LOAD_MORE_PRODUCTS";
